# Generated by Django 5.0.6 on 2024-06-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.IntegerField()),
                ("model", models.CharField(max_length=50)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="RawPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shoot_time", models.DateTimeField(blank=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("modify_time", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.FilePathField(
                        blank=True,
                        match="*.jpg",
                        null=True,
                        path="/path/to/existing/images",
                        recursive=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sduter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=20, null=True)),
                ("college", models.CharField(max_length=20, null=True)),
                ("grade", models.CharField(max_length=20, null=True)),
                ("identity", models.CharField(max_length=20, null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("qq_number", models.CharField(max_length=30, null=True)),
                ("birthday", models.DateField(null=True)),
                ("first_login", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.FilePathField()),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.rawphoto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Youtholer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=20, null=True)),
                ("department", models.CharField(max_length=20, null=True)),
                ("identity", models.CharField(max_length=20, null=True)),
                ("position", models.CharField(default="成员", max_length=20)),
                (
                    "origin_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.sduter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "member",
                    models.ManyToManyField(
                        related_name="attend_task", to="taskManager.youtholer"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burden_task",
                        to="taskManager.youtholer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rawphoto",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taskManager.youtholer"
            ),
        ),
        migrations.CreateModel(
            name="MachineAlloc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocation_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("reason", models.CharField(default="", max_length=1000)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.machine",
                    ),
                ),
                (
                    "youtholer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.youtholer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.FileField(upload_to="")),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taskManager.rawphoto",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="taskManager.youtholer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="youtholer",
            constraint=models.UniqueConstraint(
                fields=("sdut_id", "department"), name="youthol_id"
            ),
        ),
    ]
