# Generated by Django 5.0.6 on 2024-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="name",
            field=models.CharField(default="Youthol", max_length=50),
        ),
        migrations.AddField(
            model_name="machine",
            name="profile",
            field=models.FileField(default=2, upload_to="profile/machine/"),
            preserve_default=False,
        ),
    ]
