# Generated by Django 5.0.6 on 2024-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0003_remove_machine_machine_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="type",
            field=models.CharField(default="相机", max_length=50),
        ),
    ]
