# Generated by Django 5.0.6 on 2024-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taskManager",
            "0005_comment_machineborrowhistory_machineborrowrecord_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineborrowrecord",
            name="borrow_time",
            field=models.DateTimeField(),
        ),
    ]
