# Generated by Django 5.0.6 on 2024-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0007_delete_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineborrowrecord",
            name="borrow_time",
            field=models.DateTimeField(default="2023-07-03T10:15:30"),
            preserve_default=False,
        ),
    ]
