# Generated by Django 5.0.6 on 2024-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0009_alter_machineborrowrecord_borrow_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineborrowrecord",
            name="is_cancle",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="MachineBorrowHistory",
        ),
    ]
