# Generated by Django 5.0.6 on 2024-07-04 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0010_machineborrowrecord_is_cancle_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Activity",
        ),
    ]
