# Generated by Django 5.0.6 on 2024-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0011_rename_task_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
