# Generated by Django 5.0.6 on 2024-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0012_activity_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawphoto",
            name="upload_time",
        ),
        migrations.RemoveField(
            model_name="rawphoto",
            name="uploader",
        ),
        migrations.AlterField(
            model_name="rawphoto",
            name="path",
            field=models.FilePathField(
                blank=True, null=True, path="/path/to/existing/images", recursive=True
            ),
        ),
    ]
