# Generated by Django 5.0.6 on 2024-07-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taskManager",
            "0013_remove_rawphoto_upload_time_remove_rawphoto_uploader_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoprofile",
            name="path",
            field=models.FilePathField(path="/final/"),
        ),
        migrations.AlterField(
            model_name="rawphoto",
            name="path",
            field=models.FilePathField(
                blank=True, null=True, path="/final/", recursive=True
            ),
        ),
    ]
