# Generated by Django 5.0.6 on 2024-07-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0014_alter_photoprofile_path_alter_rawphoto_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoprofile",
            name="path",
            field=models.CharField(max_length=2047),
        ),
    ]
