# Generated by Django 5.0.6 on 2024-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0015_alter_photoprofile_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoprofile",
            name="path",
            field=models.FilePathField(path="/final/"),
        ),
    ]
