# Generated by Django 5.0.6 on 2024-07-05 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0016_alter_photoprofile_path"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhotoProfile",
        ),
    ]
