# Generated by Django 5.0.6 on 2024-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0017_delete_photoprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.IntegerField()),
                ("path", models.FilePathField(path="profile/")),
            ],
        ),
    ]
