# Generated by Django 5.0.6 on 2024-07-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0018_photoprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalphoto",
            name="path",
            field=models.FileField(upload_to="final/"),
        ),
        migrations.AlterField(
            model_name="rawphoto",
            name="path",
            field=models.FilePathField(
                blank=True, null=True, path="/rawphoto/", recursive=True
            ),
        ),
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_name", models.CharField(max_length=100)),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.activity",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.rawphoto",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.youtholer",
                    ),
                ),
            ],
        ),
    ]
