# Generated by Django 5.0.6 on 2024-07-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0019_alter_finalphoto_path_alter_rawphoto_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityentry",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taskManager.rawphoto",
            ),
        ),
    ]
