# Generated by Django 5.0.6 on 2024-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0020_alter_activityentry_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityentry",
            name="photo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
