# Generated by Django 5.0.6 on 2024-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0022_alter_activityentry_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityentry",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
