# Generated by Django 5.0.6 on 2024-07-07 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0025_alter_rawphoto_machine_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawphoto",
            old_name="machine_id",
            new_name="machine",
        ),
        migrations.AddField(
            model_name="activityentry",
            name="machine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taskManager.machine",
            ),
        ),
    ]
