# Generated by Django 5.0.6 on 2024-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskManager", "0026_rename_machine_id_rawphoto_machine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="alias",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
